import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Download, Search } from "lucide-react";
import { ProgressAreaChart } from "../components/Charts";

const FILTERS = ["All", "Matched", "Missing"];

const PRIORITY_STYLES = {
  High:   { bg: "rgba(244,63,94,0.1)",  text: "#fda4af", border: "rgba(244,63,94,0.2)"  },
  Medium: { bg: "rgba(245,158,11,0.1)", text: "#fcd34d", border: "rgba(245,158,11,0.2)" },
  Low:    { bg: "rgba(79,142,247,0.1)", text: "#93c5fd", border: "rgba(79,142,247,0.2)" },
};

function getPriority(skill, recommendations) {
  const time = recommendations?.[skill]?.time_to_learn ?? "";
  if (time.includes("4") || time.includes("month")) return "High";
  if (time.includes("2") || time.includes("3"))     return "Medium";
  return "Low";
}

function buildTableRows(analysis) {
  if (!analysis) return [];
  const rows = [];
  (analysis.missing_skills ?? []).forEach(skill => {
    const rec = analysis.recommendations?.[skill] ?? {};
    rows.push({ skill, status: "Missing", priority: getPriority(skill, analysis.recommendations), time: rec.time_to_learn ?? "—" });
  });
  (analysis.matched_skills ?? []).forEach(skill => {
    rows.push({ skill, status: "Matched", priority: "—", time: "—" });
  });
  return rows;
}

function exportPDF(analysis, tableRows) {
  const matched   = tableRows.filter(r => r.status === "Matched").length;
  const missing   = tableRows.filter(r => r.status === "Missing").length;
  const total     = tableRows.length;
  const matchRate = analysis?.match_percentage ?? Math.round((matched / total) * 100);
  const domain    = analysis?.job_domain ?? "General";
  const readiness = analysis?.job_readiness ?? "—";
  const timeReady = analysis?.estimated_time_to_job_ready ?? "—";
  const advice    = analysis?.career_advice ?? "";
  const recs      = analysis?.recommendations ?? {};
  const date      = new Date().toLocaleDateString();

  const skillRows = tableRows.map(r => `
    <tr>
      <td>${r.skill}</td>
      <td style="color:${r.status === "Matched" ? "#059669" : "#dc2626"};font-weight:600">
        ${r.status === "Matched" ? "✓" : "✕"} ${r.status}
      </td>
      <td style="color:${r.priority === "High" ? "#dc2626" : r.priority === "Medium" ? "#b45309" : "#3b82f6"}">
        ${r.priority}
      </td>
      <td>${r.time}</td>
    </tr>`).join("");

  const recRows = Object.entries(recs).map(([skill, d]) => `
    <tr>
      <td><strong>${skill}</strong></td>
      <td>${d.youtube_title ?? "—"}</td>
      <td>${d.certificate_name ?? "—"}</td>
      <td>${d.time_to_learn ?? "—"}</td>
    </tr>`).join("");

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>SkillGap Report</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Arial, sans-serif; color: #1e1e3c; background: #fff; padding: 0; }

  .header {
    background: linear-gradient(135deg, #4f8ef7, #6366f1);
    color: white;
    padding: 28px 32px;
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
  }
  .header h1 { font-size: 24px; font-weight: 800; margin-bottom: 4px; }
  .header p  { font-size: 12px; opacity: 0.8; }
  .header-right { text-align: right; font-size: 12px; }

  .cards {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 12px;
    padding: 24px 32px 0;
  }
  .card {
    background: #f5f6fa;
    border-radius: 10px;
    padding: 14px 16px;
    text-align: center;
  }
  .card .val  { font-size: 26px; font-weight: 800; color: #1e1e3c; }
  .card .lbl  { font-size: 10px; color: #888; text-transform: uppercase; margin-top: 3px; }

  .advice {
    margin: 20px 32px 0;
    background: #eff6ff;
    border-left: 4px solid #6366f1;
    border-radius: 8px;
    padding: 12px 16px;
    font-size: 12px;
    color: #1e3a5f;
    line-height: 1.5;
  }

  .section { padding: 20px 32px 0; }
  .section h2 { font-size: 14px; font-weight: 700; margin-bottom: 10px; color: #1e1e3c; }

  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th {
    background: #4f8ef7;
    color: white;
    padding: 8px 12px;
    text-align: left;
    font-size: 11px;
    font-weight: 600;
    text-transform: uppercase;
  }
  td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; }
  tr:nth-child(even) td { background: #f8f9fc; }

  .rec-table th { background: #6366f1; }

  .footer {
    margin-top: 32px;
    padding: 14px 32px;
    background: #f9fafb;
    border-top: 1px solid #e5e7eb;
    font-size: 11px;
    color: #aaa;
    text-align: center;
  }

  @media print {
    body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    @page { margin: 0; size: A4; }
  }
</style>
</head>
<body>

<div class="header">
  <div>
    <h1>Skill Gap Report</h1>
    <p>Generated by SkillGap AI &nbsp;·&nbsp; ${date}</p>
  </div>
  <div class="header-right">
    <div><strong>Domain:</strong> ${domain}</div>
    <div><strong>Readiness:</strong> ${readiness}</div>
    <div><strong>Time to Ready:</strong> ${timeReady}</div>
  </div>
</div>

<div class="cards">
  <div class="card"><div class="val">${total}</div><div class="lbl">Total Skills</div></div>
  <div class="card"><div class="val" style="color:#059669">${matched}</div><div class="lbl">Matched</div></div>
  <div class="card"><div class="val" style="color:#dc2626">${missing}</div><div class="lbl">Missing</div></div>
  <div class="card"><div class="val" style="color:#6366f1">${matchRate}%</div><div class="lbl">Match Rate</div></div>
</div>

${advice ? `<div class="advice"><strong>💡 Career Advice:</strong> ${advice}</div>` : ""}

<div class="section">
  <h2>Skill Analysis</h2>
  <table>
    <thead><tr><th>Skill</th><th>Status</th><th>Priority</th><th>Time to Learn</th></tr></thead>
    <tbody>${skillRows}</tbody>
  </table>
</div>

${recRows ? `
<div class="section">
  <h2>Recommendations</h2>
  <table class="rec-table">
    <thead><tr><th>Skill</th><th>Video Resource</th><th>Certificate</th><th>Time</th></tr></thead>
    <tbody>${recRows}</tbody>
  </table>
</div>` : ""}

<div class="footer">SkillGap AI &nbsp;·&nbsp; ${date}</div>

</body>
</html>`;

  const win = window.open("", "_blank");
  win.document.write(html);
  win.document.close();
  win.onload = () => {
    win.focus();
    win.print();
  };
}

export default function Reports({ analysis }) {
  const [filter, setFilter] = useState("All");
  const [search, setSearch] = useState("");

  const tableRows = buildTableRows(analysis);
  const filtered  = tableRows.filter(
    r => (filter === "All" || r.status === filter) &&
         r.skill.toLowerCase().includes(search.toLowerCase())
  );

  const matched   = tableRows.filter(r => r.status === "Matched").length;
  const missing   = tableRows.filter(r => r.status === "Missing").length;
  const total     = tableRows.length;
  const matchRate = total > 0 ? analysis?.match_percentage ?? Math.round((matched / total) * 100) : 0;

  if (!analysis) {
    return (
      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}
        className="flex flex-col items-center justify-center gap-4"
        style={{ minHeight: 320 }}>
        <div style={{
          width: 64, height: 64, borderRadius: "50%",
          background: "rgba(99,102,241,0.1)", border: "1px solid rgba(99,102,241,0.2)",
          display: "flex", alignItems: "center", justifyContent: "center", fontSize: 28,
        }}>📊</div>
        <div style={{ textAlign: "center" }}>
          <p style={{ color: "var(--text-primary)", fontWeight: 600, fontSize: 15, marginBottom: 6 }}>No report yet</p>
          <p style={{ color: "var(--text-secondary)", fontSize: 13 }}>Upload your resume and job description to generate a report.</p>
        </div>
      </motion.div>
    );
  }

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}
      className="px-4 py-5 sm:px-6 lg:px-8 max-w-6xl mx-auto space-y-5">

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center gap-3 sm:justify-between">
        <div>
          <h1 className="text-xl sm:text-2xl font-bold mb-0.5"
            style={{ color: "var(--text-primary)", letterSpacing: "-0.02em" }}>Reports</h1>
          <p className="text-xs sm:text-sm" style={{ color: "var(--text-secondary)" }}>
            Detailed skill gap analysis and progress tracking
          </p>
        </div>
        <motion.button
          whileTap={{ scale: 0.97 }}
          onClick={() => exportPDF(analysis, tableRows)}
          className="flex items-center justify-center gap-2 rounded-xl text-white text-sm font-semibold self-start sm:self-auto"
          style={{ height: 44, paddingLeft: 16, paddingRight: 16, background: "linear-gradient(135deg, #4f8ef7, #6366f1)" }}>
          <Download size={14} /> Export PDF
        </motion.button>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        {[
          { label: "Total Skills", value: total,          color: "var(--text-primary)" },
          { label: "Matched",      value: matched,         color: "#6ee7b7" },
          { label: "Missing",      value: missing,         color: "#fda4af" },
          { label: "Match Rate",   value: `${matchRate}%`, color: "#93c5fd" },
        ].map(({ label, value, color }, i) => (
          <motion.div key={label} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.07 }}
            className="rounded-2xl p-4"
            style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.07)" }}>
            <p className="text-xl sm:text-2xl font-bold mb-0.5" style={{ color }}>{value}</p>
            <p className="text-[11px] font-medium" style={{ color: "var(--text-muted)" }}>{label}</p>
          </motion.div>
        ))}
      </div>

      {/* Table card */}
      <div className="rounded-2xl overflow-hidden"
        style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.07)" }}>

        {/* Toolbar */}
        <div className="flex flex-col sm:flex-row gap-3 p-4"
          style={{ borderBottom: "1px solid rgba(255,255,255,0.07)" }}>
          <div className="flex items-center gap-2 flex-1 rounded-xl px-3"
            style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)", height: 40 }}>
            <Search size={13} className="text-white/30 shrink-0" />
            <input value={search} onChange={e => setSearch(e.target.value)}
              placeholder="Search skills…"
              className="flex-1 bg-transparent text-sm text-white placeholder-white/25 focus:outline-none"
              aria-label="Search skills" />
          </div>
          <div className="flex gap-1 bg-white/5 rounded-xl p-1" role="group">
            {FILTERS.map(f => (
              <button key={f} onClick={() => setFilter(f)}
                className="flex-1 sm:flex-none text-xs font-semibold px-3 rounded-lg transition-all"
                style={{
                  height: 32,
                  background: filter === f ? "rgba(99,102,241,0.3)" : "transparent",
                  color:      filter === f ? "#c7d2fe" : "rgba(200,200,220,0.4)",
                  border:     filter === f ? "1px solid rgba(99,102,241,0.3)" : "1px solid transparent",
                }}>
                {f}
              </button>
            ))}
          </div>
        </div>

        {/* Table */}
        <div className="overflow-x-auto">
          <table className="w-full text-sm" style={{ minWidth: 400 }}>
            <thead>
              <tr style={{ borderBottom: "1px solid rgba(255,255,255,0.07)" }}>
                {["Skill", "Status", "Priority", "Time"].map(h => (
                  <th key={h} className="text-left px-4 py-3 text-[11px] font-semibold uppercase tracking-wider"
                    style={{ color: "var(--text-muted)" }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              <AnimatePresence>
                {filtered.map((row, i) => (
                  <motion.tr key={row.skill}
                    initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                    transition={{ delay: i * 0.025 }}
                    style={{ borderBottom: "1px solid rgba(255,255,255,0.04)" }}>
                    <td className="px-4 py-3.5 font-semibold text-white text-sm">{row.skill}</td>
                    <td className="px-4 py-3.5">
                      <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold"
                        style={row.status === "Matched"
                          ? { background: "rgba(16,185,129,0.1)", color: "#6ee7b7", border: "1px solid rgba(16,185,129,0.2)" }
                          : { background: "rgba(244,63,94,0.1)",  color: "#fda4af", border: "1px solid rgba(244,63,94,0.2)" }}>
                        {row.status === "Matched" ? "✓" : "✕"} {row.status}
                      </span>
                    </td>
                    <td className="px-4 py-3.5">
                      {row.priority !== "—" ? (
                        <span className="text-[11px] px-2 py-0.5 rounded-lg font-semibold"
                          style={PRIORITY_STYLES[row.priority]
                            ? { background: PRIORITY_STYLES[row.priority].bg, color: PRIORITY_STYLES[row.priority].text, border: `1px solid ${PRIORITY_STYLES[row.priority].border}` }
                            : { color: "var(--text-muted)" }}>
                          {row.priority}
                        </span>
                      ) : <span style={{ color: "var(--text-muted)" }}>—</span>}
                    </td>
                    <td className="px-4 py-3.5 text-xs" style={{ color: "var(--text-secondary)" }}>{row.time}</td>
                  </motion.tr>
                ))}
              </AnimatePresence>
            </tbody>
          </table>
          {filtered.length === 0 && (
            <div className="py-12 text-center text-sm" style={{ color: "var(--text-muted)" }}>
              No skills match your filter
            </div>
          )}
        </div>
      </div>

      {/* Progress chart */}
      <div className="rounded-2xl p-4 sm:p-6"
        style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.07)" }}>
        <h3 className="text-sm font-semibold mb-1" style={{ color: "var(--text-primary)" }}>Learning Trajectory</h3>
        <p className="text-xs mb-5" style={{ color: "var(--text-muted)" }}>Projected readiness over 7 weeks</p>
        <ProgressAreaChart gradientId="reportsGradMobile" height={180} />
      </div>

    </motion.div>
  );
}